# Generated by Django 5.0.1 on 2024-01-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_djname_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_level',
            field=models.CharField(choices=[('none', 'None'), ('user', 'User'), ('exec', 'Exec'), ('admin', 'Admin')], default='User', max_length=5),
        ),
    ]
