# Generated by Django 5.0.1 on 2024-01-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='djname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
