# Generated by Django 5.0.1 on 2024-01-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_djname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_level',
            field=models.CharField(choices=[('none', 'None'), ('user', 'User'), ('exec', 'Exec'), ('admin', 'Admin')], default='user', max_length=5),
        ),
    ]
