# Generated by Django 5.0.1 on 2024-01-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('artist', 'short_name')},
        ),
    ]
