# Generated by Django 5.0.1 on 2024-01-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_artist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
