# Generated by Django 5.0.1 on 2024-01-30 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_artist_comment_label_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='highest_chart_position',
        ),
        migrations.AlterField(
            model_name='album',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
